### PR TITLE
Link to current roadmap

### PR DESCRIPTION
**Pull request by gdestuynder**

### CODE REVIEW

**Comment by hmitsch** [comment]
@gdestuynder that new link does not work for me. Do I need to get access to that document first?

**Comment by gdestuynder** [comment]
@hmitsch yes, or login to productplan (via sso.mozilla.com)

**Comment by hmitsch** [comment]
@gdestuynder how about linking the public viewable URL for the Roadmap?

**Comment by gdestuynder** [comment]
not against it, i suspect this is supported now. @jeffbryner would that be ok?

**Comment by jeffbryner** [comment]
WFM!

**Comment by gdestuynder** [comment]
@hmitsch done

**Pull request merged**
